version: '3'


services:
  redis:
    image: 'redis:alpine'

  web:
    build: .
    ports:
      - '8000:8000'
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - '.:/var/service'
    command: 'gunicorn -b 0.0.0.0:8000 cloudService.wsgi'

  celery_beat:
    build: .
    links:
      - redis
    depends_on:
      - redis
    volumes_from:
      - web
    command: 'celery -A asynchronous beat'

  celery_login:
    build: .
    links:
      - redis
    depends_on:
      - redis
    volumes_from:
      - web
    command: 'celery -A asynchronous worker -Q token -P solo --loglevel=info'

  celery_worker:
    build: .
    links:
      - redis
    depends_on:
      - redis
      - celery_login
      - celery_beat
    volumes_from:
      - web
    command: 'celery -A asynchronous worker -Q game -c 15 --loglevel=info'


